//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public decimal order_id { get; set; }
        public decimal shipping_id { get; set; }
        public decimal pd_id { get; set; }
        public Nullable<decimal> voucher_id { get; set; }
        public Nullable<double> UnitPriceSale { get; set; }
        public Nullable<double> QuantitySale { get; set; }
        public Nullable<System.DateTime> order_created { get; set; }
    
        public virtual product product { get; set; }
        public virtual shipping shipping { get; set; }
        public virtual voucher voucher { get; set; }
    }
}
