//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.shippings = new HashSet<shipping>();
        }
    
        public decimal users_id { get; set; }
        public string users_password { get; set; }
        public string users_email { get; set; }
        public string users_fullname { get; set; }
        public string users_phone { get; set; }
        public Nullable<int> users_gender { get; set; }
        public Nullable<System.DateTime> users_birthday { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipping> shippings { get; set; }
    }
}
